/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.nageoffer.ai.ragent.agent.tool;

import com.nageoffer.ai.ragent.agent.domain.AgentToolResult;
import com.nageoffer.ai.ragent.agent.domain.KnowledgeOpsContext;

import java.util.Map;

public interface AgentTool {

    String name();

    String type();

    default String description() {
        return name();
    }

    default Map<String, String> inputSchema() {
        return Map.of(
                "kbId", "Target knowledge base id.",
                "task", "Knowledge operation task or evaluation objective.",
                "topK", "Maximum evidence chunks to retrieve when the tool needs retrieval."
        );
    }

    default Map<String, String> outputSchema() {
        return Map.of(
                "summary", "Human-readable tool execution summary.",
                "data", "Structured diagnostic data generated by the tool."
        );
    }

    default boolean supportRetry() {
        return false;
    }

    default int timeoutSeconds() {
        return 30;
    }

    AgentToolResult execute(KnowledgeOpsContext context);
}
